### ISSUE TITLE
service on windows can not be started

### ISSUE THREAD

**Issue by callmejobshen** [alexsilva/supervisor#38] opened 2021-06-16 00:51 UTC
Hi Alex,

I installed supervisor-win 4.6.0 on windows 10 enterprise @2019.

then i ran following commands in a "Elevated" dos command window

echo_supervisord_conf.exe > supervisord.conf
more supervisord.conf
python -m supervisor.services install -c supervisord.conf

I got following output

Installing service Supervisor Pyv3.9
Changing service configuration
Service updated

And i could see the service was added to windows service.

Then i ran C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\services.msc Elevated, so that i can have the permission to start the service.

But when i click the start, i received following error message immediately

Windows could not start the Supervisor Pyv3.9 process monitor service on Local Computer
Error 1053: The service did not respond to the start or control request in a timely fashion.

I wonder what could be wrong, and if i can not use it as windows service, can i use something like "supervisiorctl start" to manually start the programs, assume i add my programs to the program section?

thanks,
Job

**Comment by callmejobshen** [comment] 2021-06-16 00:54
![supervisor-win-fail](https://user-images.githubusercontent.com/85972645/122141708-bfea6c80-ce02-11eb-8f77-bfac6205e50d.png)

**Comment by callmejobshen** [comment] 2021-06-16 00:58
![supervisor-win-fail](https://user-images.githubusercontent.com/85972645/122141943-40a96880-ce03-11eb-879a-5e71ac7d1506.png)

**Comment by alexsilva** [comment] 2021-06-16 12:04
The path to the supervisor.conf file must be absolute.
`python -m supervisor.services install -c c:\supervisord.conf or d:\supervisord.conf`

Otherwise the execution failure will be in a log file in the python directory.

**Comment by callmejobshen** [comment] 2021-06-16 19:34
Thank you Alex.

I removed and reinstalled the service with the absolute path, still got the same error. See screen shot.

Where can i find the log file?  The Scripts or Lib\site-packages\supervisor has no log file.

![supervisor-win-fail2](https://user-images.githubusercontent.com/85972645/122281047-b0206600-ce9e-11eb-9097-4d877b5d92a7.png)

**Comment by alexsilva** [comment] 2021-06-16 20:19
The log in your case is in the c:\test directory.

I noticed that your setup has a virtual environment and may be causing the issue.

**Comment by callmejobshen** [comment] 2021-06-17 17:50
I repeated it without virtual environment, and got a different error.

I don't know what file it was trying to access, and maybe because the service could not started, there is no log file under c:\test.

![supervisor-win-fail3](https://user-images.githubusercontent.com/85972645/122448539-b6bfe380-cf59-11eb-99c4-1948405ab1df.png)

**Comment by alexsilva** [comment] 2021-06-17 19:11
This error is difficult to solve because the service is failing before generating the log file.
What you can do is try to run the supervisor on the terminal

If the command below runs without fail, it means that the problem is with the windows service script (`supervisor.services`)
`python -m supervisor.supervisord -c c:\test\supervisord.conf`

The only solution in this case is to use a debugger tool to find the fault location.
https://tamentis.com/projects/rpdb/
https://github.com/tamentis/rpdb
https://docs.python.org/3/library/pdb.html

You would have to install the package and import it at the beginning of the script `supervisor.services`.
`import rpdb; rpdb.set_trace()`

**Comment by alexsilva** [comment] 2021-06-17 21:12
I was also seeing similar errors and just run
```
python -m supervisor.services
```
and the service initialization worked.
 Sometimes the windows apis behave strangely.

**Comment by alexsilva** [comment] 2021-06-18 00:06
I made some changes that might solve your problem. Need to test.

https://github.com/alexsilva/supervisor/commits/windows

`python -m pip install git+https://github.com/alexsilva/supervisor@windows -U`

**Closed as completed** 2021-07-17 22:29 UTC
